apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "kube-manifest-backup.fullname" . }}-resources-configmap
data:
    resources.yaml: |-
        resources:
        {{- range .Values.global.backupResources }}
          - namespaces: {{ .namespaces | toYaml | nindent 12 }}
            group: "{{ .group }}"
            version: "{{ .version }}"
            resource: "{{ .resource }}"
            secret: {{ .secret }}
        {{- end }}
