apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-manifest-backup.fullname" . }}-s3-config-secret
  labels:
    app.kubernetes.io/name: {{ include "kube-manifest-backup.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  s3-config.json: |
    {{- $config := dict }}
    {{- range $key, $value := .Values.global.s3.config }}
    {{- $_ := set $config $key $value }}
    {{- end }}
    {{ $config | toJson | b64enc }}
